### ISSUE TITLE
Subdivision empty for a lot of cities

### ISSUE THREAD

**Issue by Bramzor** [datasets/un-locode#11]
Subdivision is empty for a lot of cities while it actually shouldn't be. For example these Dutch cities:
![image](https://cloud.githubusercontent.com/assets/5624708/19191492/f9ed2b08-8ca2-11e6-940e-e6c31bf30f36.png)
Any reason why this is the case?
I think I can fill up this information by using Google for receiving the province of every city. Is it allowed to have a pull request to update this information?

**Comment by sabas** [comment]
It is empty because no one has ever filled that column in the original dataset... To 'fix' this upstream it would need to fill a DMR with the UNECE secretariat (see here http://www.unece.org/cefact/locode/welcome.html).

**Comment by rgrp** [comment]
FIXED.

@Bramzor thanks for raising - it is good to get these things clarified and thanks a lot to @sabas for an excellent answer which I think clarifies that this is an upstream issue.

**Comment by Bramzor** [comment]
I could fill in this information via Google API's and some scripting. But I'm not going to fill in documents manually to have this changed upstream. In that case, I think it's better that I just create a fork from this project and create a script that will inject the updated information. Because people can't use this one as information is just incomplete and process to get this upstream seems hard. Don't think that everyone can just submit this information anyway so, would be a waste of time. Or you guys should be open for a pull request with a script that can inject this additional information (province information) into the current dataset files?

**Comment by sabas** [comment]
I don't know what the policy is in this cases, @rgrp should answer...

IMHO script to 'augment' the dataset could fit in the repository, or you can mantain an augmented fork, but directly modifying the data would make it harder when upgrading to a newer release.

Personally I'm working to embed un-locodes in Wikidata (just for italy right now) to try and see what I can do with the SPARQL interface, and I've discussed some of these data issues at the conference in Geneva this year.
