### ISSUE TITLE
Double unlocode AXMHQ

### ISSUE THREAD

**Issue by aphofstede** [datasets/un-locode#17]
I believe countrycode/unlocode pairs should be unique?

> ,AX,MHQ,Maarianhamina (Mariehamn),Maarianhamina (Mariehamn),,AI,1--4----,1207,,6006N 01957E,
> ,AX,MHQ,Mariehamn (Maarianhamina),Mariehamn (Maarianhamina),,AI,1--4----,1207,,6006N 01957E,

**Comment by sabas** [comment]
Yes, it is unique, but they're providing an alternative name. It's common, see also ITFCO

**Comment by aphofstede** [comment]
Ah I see, I’ll have to modify our importer a bit then. thanks!
