### ISSUE TITLE
Plotting LOCODES on a map

### ISSUE THREAD

**Issue by planemad** [datasets/un-locode#19]
First off, this is such a valuable dataset to understand the economic hotspots of the world. Out of curiosity, i tried to plot all the locations on a map, but looks like the coordinates provided in the source requires quite a bit of cleanup:

- Coordinate precision is around 2 decimal places (>1km of accuracy) and mostly
- 24827/111178 (22%) missing coordinates. Could fill in coordinates for around 2000 using [IATA locations](https://data.humdata.org/dataset/global-airports)
- Plotting the locations reveals many incorrect locations, either northing/easting is swapped or some other data entry error.

Anyway, for those interested here is a first attempt at making a map:

<img width="895" alt="Screen Shot 2020-05-18 at 7 49 54 PM" src="https://user-images.githubusercontent.com/126868/82269820-d17fed00-9940-11ea-9f63-c1adf25762d1.png">
<img width="737" alt="Screen Shot 2020-05-18 at 7 50 05 PM" src="https://user-images.githubusercontent.com/126868/82269824-d775ce00-9940-11ea-9a28-e7f6af43ea85.png">

[view map](https://api.mapbox.com/styles/v1/planemad/ckaaoy7n901ra1io6xs730iew.html?fresh=true&title=view&access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#3.73/21.05/85.05)

CSV: https://github.com/planemad/un-locode/blob/master/data/geo/code-list-geo.csv

Feel free to open an issue at the fork^ for any ideas to cleanup the CSV or maintain a geojson of the data.

**Comment by sabas** [comment]
Hi Arun, I remember your name from OSM :-)
The geographic analysis was my first attempt at fixing this dataset at the source (I'm in the UN/LOCODE advisory group) and I suggested to increase the coordinate precision, but it wasn't accepted in the Recommendation revision (the "specification" of the dataset. Now my interpretation from the geo side is to interpret/assign codes to municipal entities first and in special cases to locations which are important for international trade but aren't municipal seat.
If you want to chat on the topic feel free to reach me via email.

**Comment by cristan** [comment]
What about the GPS coordinates who are wrong? Is there any way to report these? I'd rather have no data than wrong data.

**Comment by sabas** [comment]
@cristan The system to review data is called DMR and is available here https://apps.unece.org/unlocode/ (there were some improvements to be released in the future)
Review is done in 2 cycles per year, so expect ~6 months for a feedback.

**Comment by cristan** [comment]
> Feel free to open an issue at the fork^ for any ideas to cleanup the CSV or maintain a geojson of the data.
@planemad 
I can't :( Issues doesn't seem to be turned on.

I was gonna ask you about the airport data source you've used. It seems like they have IATA's in that dataset, but I can't figure out how to get that in the response, and therefore how to make the link with the unlocode. How did you do it?
