### ISSUE TITLE
CSV contains two lists with two different formats

### ISSUE THREAD

**Issue by dwaam** [datasets/un-locode#34]
Hi, 

There is an issue with the CSV export for resource `code-list`:
Header: 
`Change,Country,Location,Name,NameWoDiacritics,Subdivision,Status,Function,Date,IATA,Coordinates,Remarks`
for around 61K lines

then a new header appears at line 61396
`Change,Country,Location,Name,NameWoDiacritics,Subdivision,Function,Status,Date,IATA,Coordinates,Remarks`

Same data but two header are switched. 

Is there a way to fix that please? 

I see that it is directly the data file which is corrupted:
https://raw.githubusercontent.com/datasets/un-locode/refs/heads/main/data/code-list.csv

Thank

**Comment by sabas** [comment]
Good catch! @gradedSystem please check Thanks

**Comment by gradedSystem** [comment]
@sabas should be fixed with the latest PR https://github.com/datasets/un-locode/pull/35

**Comment by dwaam** [comment]
Hi, 
Thanks for the PR, but I don't think the data is fixed. 
The second header is removed, but the problem is that two columns are switched, so all the next data should have the two columns switched back no?

**Comment by gradedSystem** [comment]
ok now i think i understood @dwaam

**Comment by gradedSystem** [comment]
@dwaam I added function to fix this issue raised a PR waiting for an approve

**Comment by dwaam** [comment]
Alright thanks, yep, now the data seems all good in the csv thanks ;)
